name: Weekly update for last commit date

on:
  schedule:
    # Runs every Monday at 5 AM UTC
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  update-last-commit-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run script
        run: bun utils/updateLastCommitDate.ts

      - name: Check for Changes
        id: changes
        run: |
          # Exit if no changes were made by the script
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Branch, Commit, and Push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          branch_name="data/updates-last-commit-date"
          git checkout -b $branch_name
          git add data/
          git commit -m "chore: automated project data update"
          git push origin $branch_name --force

      - name: Create Pull Request
        id: pullrequest
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: $branch_name
          base: main
          title: "data: Automated Weekly last commit date update"
          body: |
            Auto-generated PR with data updates. Review before merging!
            - **Triggered by:** Scheduled workflow
            - **Command:** `bun utils/updateLastCommitDate.ts`

      - name: Comment on PR with data update issues
        if: steps.changes.outputs.has_changes == 'true'
        env:
          PR_NUMBER: ${{ steps.pullrequest.outputs.pull-request-number }}
        run: |
          if [ -f errors.txt ]; then
            script_errors=$(cat errors.txt)
            gh pr comment $PR_NUMBER --body "⚠️ **Note:** We faced these issues while updating the data. Maybe it needs your attention:
            \`\`\`
            $script_errors
            \`\`\`"
          else
            echo "Finished with no issues at all! :)"
          fi
