name: Weekly update for last commit date

on:
  schedule:
    # Runs every Monday at 5 AM UTC
    - cron: "0 5 * * 1"
  workflow_dispatch:

env:
  BRANCH_NAME: "data/weekly-last-commit-date-update-${{ github.run_id }}"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-last-commit-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run script
        id: run
        run: bun utils/updateLastCommitDate.ts
      - name: Check for Changes
        id: changes
        run: |
          # Exit if no changes were made by the script
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: pullrequest
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ env.BRANCH_NAME }}
          commit-message: "data: automatically update last commit date of projects"
          title: "data: Automated Weekly last commit date update"
          body: |
            Auto-generated PR with data updates. Review before merging!
            - **Triggered by:** Scheduled workflow
            - **Command:** `bun utils/updateLastCommitDate.ts`
      - name: Comment on PR with data update issues
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.pullrequest.outputs.pull-request-number }}
          body: |
            ⚠️ **Note:** We faced these issues while updating the data. Maybe it needs your attention
            ```log
            ${{ steps.run.outputs.stderr }}
            ```

          reactions: "+1"
