name: Weekly update for secret stuff

env:
  BRANCH_NAME: "test-branch-$(date +%s)"
on:
  schedule:
    # Runs every Monday at 5 AM UTC
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  update-last-commit-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Run script
        run: echo "Hello, world $(date)" >> logs.txt

      - name: Check for Changes
        id: changes
        run: |
          # Exit if no changes were made by the script
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create Branch, Commit, and Push
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$branch_name"
          git add logs.txt
          git commit -m "chore: automated updates"
          git push origin "$branch_name"

      - name: Create Pull Request
        id: pullrequest
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "$branch_name"
          base: main
          title: "data: Automated Weekly Update"
          body: |
            Auto-generated PR with logs updates. Review before merging!
            - **Triggered by:** Scheduled workflow
            - **Author: ** ${{ github.actor }}
            - **Date:** $(date)
            - **Commit:** $(git log --format="%H" -n 1)
            - **Changes:** $(git diff --name-only HEAD^)
